openapi: 3.0.0

info:
  title: Микросервис авторизации API
  version: 1.0.0
  contact:
    name: Kayot Klimenko
    email: geor.klimenko2017@yandex.ru
  description: |
    Этот API предназначен для управления аутентификацией и пользователями.
    Включает эндпоинты для входа, регистрации и работы с данными пользователей.

tags:
  - name: auth
    description: Аутентификация и регистрация пользователей.
  - name: users
    description: Работа с данными о пользователях.

paths:
  /auth/login:
    $ref: "./paths/login.yaml"